version: 2.1

executors:
  default:
    working_directory: ~/cells-selector
    docker:
      - image: circleci/node:16.14.2

caches:
  - &npm_cache cells-selector-v1-{{ checksum "package-lock.json" }}

commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          key: *npm_cache
      - run:
          name: Installing Packages
          command: npm i
      - save_cache:
          key: *npm_cache
          paths:
            - ./node_modules

  typescript:
    steps:
      - run:
          name: Checking TypeScript
          command: npm run tsc
  linters:
    steps:
      - run:
          name: Running linters
          command: npm run lint
  tests:
    steps:
      - run:
          name: Running tests
          command: npm run test

jobs:
  typescript:
    executor: default
    steps:
      - defaults
      - typescript
  linters:
    executor: default
    steps:
      - defaults
      - linters
  tests:
    executor: default
    steps:
      - defaults
      - tests

workflows:
  version: 2.1
  main:
    jobs:
      - typescript
      - linters:
          requires:
            - typescript
      - tests:
          requires:
            - linters
